                           NUMPY ndarray
A List is a python data structure that holds many python objects.It is flexible(can be filled with data of desired type).Numpy arrays lack flexibility but are much more efficient for storing and manipulating data.
Numpy-Numerical python is the fundamental package for scientific computing with python . If you are going to work on data analysis or machine learning projects, then having a solid understanding of numpy is nearly mandatory.

The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not.
That means, if you apply a function it is performed on every item in the array, rather than on the whole array object.
Numpy provides the excellent ndarray objects, short for n-dimensional arrays.
In an ‘ndarray’ object we can store multiple items of the same data type.

                Creating nd arrays

In [3]:
#create a list
import numpy as np
l = [1,2,3,4,5]
print(l)
#create an ndarray through the list
arr1 =np.array(l)
print(arr1)
print("Datatype of the ndarray:")
print(arr1.dtype)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
Datatype of the ndarray:
int32


                   Data types for nd arrays
NumPy supports a no. of numerical types. Some of them are:
1. int8
2. int16
3. int32
4. int64
5. unit8
6. unit16
7. float16
8. float32
9. complex_
10. float_

In [ ]:
#Examples

In [4]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a1.dtype

dtype('int32')

In [5]:
a2 = np.array([1.0,2,3,4,5,6,7,8,9,10])
a2.dtype

dtype('float64')

In [7]:
a3 = np.array(['a','b'])
a3.dtype

dtype('<U1')

In [9]:
#setting the data type
a4 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.float64)
a4.dtype

dtype('float64')

In [11]:
a5 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.int64)
a5.dtype

dtype('int64')

              Arithmetic with numpy arrays

In [12]:
b1= a1+a2
b1

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [13]:
b2= a1*a2
b2

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

                      Indexing and slicing
Three types of indexing methods are available in numpy:
1. field access
2. basic slicing
3. advanced indexing.

If only one parameter is used, a single item corresponding to the index will be returned. If a ':' is inserted in front of it, all items from that index onwards will be extracted. If two parameters (with : between them) is used, items between the two indexes (not including the stop index) with default step one are sliced.

In [15]:
a= np.arange(15)
print(a[0])
print(a[1:9])

0
[1 2 3 4 5 6 7 8]


In [16]:
a[0:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

Numpy supports lots of built in functions some of them are:
1. String functions:
a) add()
b) lower()
c) upper()
d) split()
e) join()

2. Mathematical functions:
a) sin()
b) arcsin()
c) degrees()
d) around()
e) floor()

3. Statistical functions
a) amin()
b) amax()
c) ptp()
d) mean()
e) median()

In [21]:
import numpy as np 
arr = np.arange(100)
arr = np.square(arr)
print(arr)

[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]


In [22]:
arr = np.array([[1,2,3],[3,4,5],[4,5,6],[7,8,9]]) 
print('mean() function:') 
print(np.mean(arr) )
print('average() function:') 
print(np.average(a))

mean() function:
4.75
average() function:
7.0


In [23]:
arr = np.array([[1,2,3],[3,4,5],[4,5,6],[7,8,9]]) 
print('sin() function:') 
print(np.sin(arr) )

sin() function:
[[ 0.84147098  0.90929743  0.14112001]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
