In [1]:
import numpy as np

This repo contains an introduction to [Jupyter](https://jupyter.org) and [IPython](https://ipython.org).

Outline of some basics:

* [Notebook Basics](../examples/Notebook/Notebook%20Basics.ipynb)
* [IPython - beyond plain python](../examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb)
* [Markdown Cells](../examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)
* [Rich Display System](../examples/IPython%20Kernel/Rich%20Output.ipynb)
* [Custom Display logic](../examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb)
* [Running a Secure Public Notebook Server](../examples/Notebook/Running%20the%20Notebook%20Server.ipynb#Securing-the-notebook-server)
* [How Jupyter works](../examples/Notebook/Multiple%20Languages%2C%20Frontends.ipynb) to run code in different languages.

You can also get this tutorial and run it on your laptop:

    git clone https://github.com/ipython/ipython-in-depth

Install IPython and Jupyter:

with [conda](https://www.anaconda.com/download):

    conda install ipython jupyter

with pip:

    # first, always upgrade pip!
    pip install --upgrade pip
    pip install --upgrade ipython jupyter

Start the notebook in the tutorial directory:

    cd ipython-in-depth
    jupyter notebook

In [2]:
import numpy as np

In [3]:
c =[1,2,3,4,5]
c

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(c)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
c1= [[1,2,3,4],[2,5,7,8]]
arr2= np.array(c1)
arr2

array([[1, 2, 3, 4],
       [2, 5, 7, 8]])

In [8]:
#Basic data types for nd arrays
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a1.dtype

dtype('int64')

In [9]:
a2 = np.array([1.0,2,3,4,5,6,7,8,9,10])
a2.dtype

dtype('float64')

In [10]:
a3 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.float64)
a3.dtype

dtype('float64')

In [11]:
a4 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = np.float32)
a4.dtype

dtype('float32')

In [12]:
a5 = np.array(['a','b'])
a5.dtype

dtype('<U1')

In [13]:
#Arithmetic operations---------------
b1= a1+a2
b1

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [14]:
b2= a1*a2
b2

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [15]:
1/b1

array([0.5       , 0.25      , 0.16666667, 0.125     , 0.1       ,
       0.08333333, 0.07142857, 0.0625    , 0.05555556, 0.05      ])

In [16]:
a1*a2*a3

array([   1.,    8.,   27.,   64.,  125.,  216.,  343.,  512.,  729.,
       1000.])

In [19]:
#indexing and slicing
a= np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
a[0]

0

In [21]:
a[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a[0:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [23]:
a[0:-2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [24]:
a[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
a[:-2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
a[0:-10]

array([0, 1, 2, 3, 4])

In [27]:
#Some numpy functions
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
arr = np.square(arr)
arr

array([       0,        1,       16,       81,      256,      625,
           1296,     2401,     4096,     6561,    10000,    14641,
          20736,    28561,    38416,    50625,    65536,    83521,
         104976,   130321,   160000,   194481,   234256,   279841,
         331776,   390625,   456976,   531441,   614656,   707281,
         810000,   923521,  1048576,  1185921,  1336336,  1500625,
        1679616,  1874161,  2085136,  2313441,  2560000,  2825761,
        3111696,  3418801,  3748096,  4100625,  4477456,  4879681,
        5308416,  5764801,  6250000,  6765201,  7311616,  7890481,
        8503056,  9150625,  9834496, 10556001, 11316496, 12117361,
       12960000, 13845841, 14776336, 15752961, 16777216, 17850625,
       18974736, 20151121, 21381376, 22667121, 24010000, 25411681,
       26873856, 28398241, 29986576, 31640625, 33362176, 35153041,
       37015056, 38950081, 40960000, 43046721, 45212176, 47458321,
       49787136, 52200625, 54700816, 57289761, 59969536, 62742

In [33]:
arr = np.sqrt(arr)
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ,
       6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
       6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ,
       7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
       7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575,
       7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
       8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386,
       8.36660027, 8.42614977, 8.48528137, 8.54400375, 8.60232

In [34]:
arr = np.array([12,24,36,48,60])
mean = arr.mean()
mean

36.0

In [35]:
res = np.sin(arr)
res

array([-0.53657292, -0.90557836, -0.99177885, -0.76825466, -0.30481062])